name: Check and Build React App

on:
  pull_request:
    branches:
      - develop 

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout kodu
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Ustawienie Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3. Cache zależności
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    # 4. Instalacja zależności
    - name: Install dependencies
      run: npm install --legacy-peer-deps

    # 6. Uruchamianie testów za pomocą React Testing Library / Jest
    - name: Run Tests
      run: npm test -- --watchAll=false

    # 7. Budowanie aplikacji (opcjonalne)
    - name: Build the project
      run: npm run build
