name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop # Akcja uruchomi się po pushu na branch develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout kodu
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Ustawienie Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3. Instalacja zależności
    - name: Install dependencies
      run: npm install --legacy-peer-deps

    # 4. Budowanie aplikacji
    - name: Build the project
      run: npm run build

    # 5. Wdrożenie na GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        force_orphan: true
